### ISSUE TITLE
Release 3.1.5-6

### ISSUE THREAD

**Issue by 130s** [start-jsk/openhrp3#43]
Waiting for https://github.com/start-jsk/openrtm_aist_core/issues/49 to be done.

**Comment by 130s** [comment]
Now ready to be released. [Pre-release job](http://jenkins.ros.org/view/Prerelease/job/prerelease-hydro-openhrp3/).

**Comment by 130s** [comment]
[Pre-release test was `unstable`](http://jenkins.ros.org/job/prerelease-hydro-openhrp3/ARCH_PARAM=amd64,UBUNTU_PARAM=precise,label=prerelease/3/consoleFull) probably because some failures occurred in downstream. As similar to [what I reported here](https://github.com/start-jsk/rtmros_common/issues/416), it's hard to tell from these failures if there's an issue within the package tested or not because some unit tests in downstream themselves are not stable. 

That said I'll release this now.

**Comment by 130s** [comment]
[Submitted](https://github.com/ros/rosdistro/pull/3870).

**Comment by 130s** [comment]
Do Groovy users also need this to be released? Personally because there's [a critical error](https://github.com/start-jsk/rtmros_common/issues/410) that is blocking OSRF's entire Groovy sync, I'm hesitating to make new release into G, at least for now.

**Comment by k-okada** [comment]
It does not needed but It always better to release them, but I understand your situation so I'll working on releasing into groovy until it becomes stable.

**Comment by 130s** [comment]
Let me be clear; I'm afraid adding new release might increase the risk of breaking the build. So I prefer to prioritizing making the buildfarm stable for Groovy.

**Comment by k-okada** [comment]
As I wrote on https://github.com/start-jsk/rtmros_common/issues/410#issuecomment-40468868, I suppose current situation is not because of groovy, but rmtros_comon itself is not enough stable. so even if we stop releasing on Groovy, it will break if we release on Hydro/Indigo and same bug fix will works for both releases.

By the way, how do we cope with https://github.com/start-jsk/hrpsys/issues/75, they want to start using trunk version of hrpsys.

One idea is to create groovy branch  on rtmros_common and stop developing/releasing and using hrpsys 315.1.x and hydro branch is continue developing on trunk (315.2.x), but this means hironx users must use groovy, so it may not acceptable.

Another idea is to create stable(315.1.x) branch on rtmros_common and only stable branch is released and deb build. This means main/core users never uses deb package. Also I afraid I mostly working on developing release so it just make you much more busy.

Another approach is to release rtmros_common and rtmros_comon_devel ?

Ideal approach is to update QNX software to 315.2.x but it may most difficult among above idea.

**Comment by 130s** [comment]
Let us continue at https://github.com/start-jsk/hrpsys/issues/76
